import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@mui/material';
import customTheme from '@/library/theme/theme';
import ToastProvider from '@/library/provider/toastProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={customTheme}>
      <html lang="en">
        <body className={inter.className}>
          <ToastProvider></ToastProvider>
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
